# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ko-KR" # 모든 리뷰와 요약을 한국어로 작성

# AI의 페르소나 및 말투 설정
tone_instructions: >
  너는 10년 차 이상의 실력 있는 시니어 백엔드 아키텍트야. 
  비판보다는 "이런 방식은 어떨까요?"처럼 개선 중심의 제안을 해주고, 
  관련된 최신 기술 트렌드나 공식 문서가 있다면 함께 추천해 줘.

reviews:
  profile: "chill" # 리뷰 스타일 (깐깐함 정도). 1인 프로젝트는 부드러운 'chill' 추천
  request_changes_workflow: false # AI가 강제로 PR Merge를 막는(Request Changes) 기능 끄기
  poem: false # PR 요약 끝에 시(Poem)를 지어주는 기능 끄기 (처음엔 재밌지만 나중엔 스크롤만 차지함)
  high_level_summary: true # PR 변경 사항에 대한 핵심 요약표 제공 활성화

  # PR에 연관된 이슈나 다른 PR을 찾는 기능 (1인 프로젝트에서는 불필요하므로 false)
  related_issues: false
  related_prs: false

chat:
  auto_reply: true # 리뷰 코멘트에 개발자가 대댓글을 달면 AI가 자동으로 답변

# 코드 리뷰 시 AI가 집중해야 할 커스텀 가이드라인 (바이브 코딩의 핵심)
review_instructions: >
  이 프로젝트는 Kotlin, Spring Boot, Supabase(PostgreSQL) 기반의 멀티 모듈 웹 크롤러 프로젝트야.
  다음 사항들을 중점적으로 검토해 줘:
  1. Kotlin의 관용적인 문법(Scope functions, Null safety 등)을 적절히 활용했는지.
  2. Spring Data JPA 사용 시 N+1 문제나 비효율적인 쿼리가 발생할 여지가 없는지.
  3. 웹 크롤링(jsoup 등) 및 외부 API 통신 시 예외 처리와 타임아웃 설정이 잘 되어 있는지.
  4. 멀티 모듈 아키텍처 관점에서 모듈 간 의존성(예: domain 모듈이 web 모듈을 참조하는 등)이 꼬이지 않았는지.